### ISSUE TITLE
Admin links table issue with links > 50 characters?

### ISSUE THREAD

**Issue by Juju-no-dev** [Antelope-Valley-College/polr#5]
Hello, I've got a problem with a freshly installed Polr (based on https://github.com/Antelope-Valley-College/polr/issues/2#issuecomment-1416516990). 

It is running with Apache 2.4.52 / PHP 8.2 on Ubuntu 22.04. I tried with MySQL 8.0.32 and MariaDB 10.6.11 (with empty databases and let setup create the tables).
The admin page table showing all links works fine until someone shortens a link longer than 50 characters.
When a link longer than 50 characters is present, the following error pops up:
DataTables warning: table id=admin_links_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

What could be the source of this?

Thanks nd have a nice day :)

**Comment by mwilmes-at-avc** [comment]
Could you confirm the size of the shortlinks column in your links table? I created a 100+ char url and was able to upload it to a new instance based on the working branch for issue #2 . It should default to 255 characters wide.

`echo "desc links;"|mysql polr`
<pre>Field   Type    Null    Key     Default Extra
id      int(10) unsigned        NO      PRI     NULL    auto_increment
short_url       varchar(255)    NO      UNI     NULL
long_url        longtext        NO              NULL</pre>

If you don't see that, you could adjust the column size to 255, but I suspect the installation isn't right. To confirm, did you switch to the issue/2-setup-is-broken branch before installing?

**Comment by mwilmes-at-avc** [comment]
If the link can be shared, would you post it?

**Comment by Juju-no-dev** [comment]
Yes,

Link :  http://exemple.fr/6

Who sends here:

https://www.google.fr/search?q=test&safe=active&sxsrf=AJOqlzWOmw82VZTTB6kikkaT_N4qde3ldg%3A1676626689101&ei=AUvvY6DYBY6dkdUP0dWTgAI&ved=0ahUKEwjg3OWRoZz9AhWOTqQEHdHqBCAQ4dUDCA8&uact=5&oq=test&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIECCMQJzIECCMQJzIKCAAQsQMQgwEQQzIECAAQQzIKCAAQsQMQgwEQQzIQCAAQgAQQFBCHAhCxAxCDATIECAAQQzIECAAQQzINCAAQgAQQFBCHAhCxAzIFCAAQgAQ6CggAEEcQ1gQQsAM6CwgAEIAEELEDEIMBOggIABCABBCxA0oECEEYAFDsBVjqB2DzCWgCcAF4AIABnwGIAZ4CkgEDMC4ymAEAoAEByAEIwAEB&sclient=gws-wiz-serp

I checked the logs but I don't get any errors.

If I delete the id that corresponds to my entry in the DATABASE, I no longer have the error.

use NAMEDATABASE;
select * from links;
DELETE from links where id=XX;

**Comment by mwilmes-at-avc** [comment]
I put this link into my test server with no problems, and I do not see any AJAX error when I go to my admin page. The original datatables.net link you posted says this error happens when the server has an error, so there may also be some info in the /storage/logs/laravel.log file. Please take a look, and if you find an error message there you think may help, please share it.

When you delete the row from your database, you are deleting your short link from your site. The error on the admin page goes away because the link isn't there anymore.

**Comment by Juju-no-dev** [comment]
Hi,
Good news, problem is solved after adding PHP extension: "mbstring".
I found the following error in the logs you mentioned:

> "[2023-02-22 12:52:31] production.ERROR: Call to undefined function Illuminate\Support\mb_strimwidth() {"exception":"[object] (Error(code: 0): Call to undefined function Illuminate\\Support\\mb_strimwidth() at /var/www/polr/vendor/laravel/framework/src/Illuminate/Support/Str.php:497)"

After adding the extension, the issue was that the destination link showed in the dashboard is truncated which is why only longer links were posing us a problem.
Closing this ticket as our install was missing one PHP extension.
Thanks for your help and have a nice day :)
